"""
BendVM instruction set.

SL(2, Z) is generated by two matrices — the classical presentation:
    S = [[0, -1], [1, 0]]      (order 4)
    T = [[1,  1], [0, 1]]      (infinite order)
Any 2×2 integer matrix with det = ±1 is a word in S and T.

The Apollonian group acting on Descartes quartets is generated by three
reflections R1, R2, R3, each a 4×4 integer matrix (one per "replace this
bend with the one on the other side of the other three circles"). Acting
on (b1, b2, b3, b4), Ri replaces bi with 2(b1+b2+b3+b4) - 3*bi - 2*other.
"""

from __future__ import annotations
from typing import Tuple

from .core import Matrix, identity


# ─────────────────────────────────────────────────────────────────────────────
#  SL(2, Z) generators
# ─────────────────────────────────────────────────────────────────────────────

# Identity (2×2)
I: Matrix = identity(2)

# S = [[0, -1], [1, 0]]  — quarter-turn, order 4 (S^4 = I)
S: Matrix = (0, -1, 1, 0)

# T = [[1, 1], [0, 1]]  — unit shear, infinite order
T: Matrix = (1, 1, 0, 1)

# T^-1 = [[1, -1], [0, 1]]
T_INV: Matrix = (1, -1, 0, 1)

# R = S * T  (commonly used in PSL(2, Z) presentations; order 3)
R: Matrix = (0, -1, 1, 1)  # = S @ T

# Fibonacci step matrix F = [[1, 1], [1, 0]] — not in SL(2, Z) literally (det = -1)
# but in GL(2, Z). Powers of F on (1, 0) give Fibonacci numbers.
FIB_STEP: Matrix = (1, 1, 1, 0)


def ST_generators() -> Tuple[Matrix, Matrix]:
    """Return (S, T) — the standard generators of SL(2, Z)."""
    return (S, T)


def sl2z_word(word: str) -> Matrix:
    """
    Compile a short string over {'S', 'T', "'"} into a 2x2 matrix.
    Example: "STSTS'" means S @ T @ S @ T @ S^-1.
    Useful for unit tests and demos of specific SL(2, Z) elements.
    """
    from .core import matmul
    result = I
    i = 0
    while i < len(word):
        ch = word[i]
        # Look ahead for '
        inverse = (i + 1 < len(word) and word[i + 1] == "'")
        if ch == 'S':
            m = S if not inverse else (0, 1, -1, 0)   # S^3 = S^-1
        elif ch == 'T':
            m = T if not inverse else T_INV
        else:
            raise ValueError(f"Unknown generator '{ch}' — use S, T, or their inverses via '")
        result = matmul(m, result)
        i += 2 if inverse else 1
    return result


# ─────────────────────────────────────────────────────────────────────────────
#  Apollonian group generators (4×4)
# ─────────────────────────────────────────────────────────────────────────────

def _apollonian_reflection(i: int) -> Matrix:
    """
    The i-th generator of the Apollonian group. Acts on a Descartes quartet
    (b1, b2, b3, b4) by replacing bi with its Descartes "partner":
        bi_new = 2*(b1 + b2 + b3 + b4) - 3*bi - 2*(bi)
               = 2*(sum of other three) - bi

    In matrix form, each Ri is the identity except that its i-th row becomes
    (2, 2, 2, 2) with a -1 in the i-th column (so Ri * b has its i-th entry
    equal to 2*Σbj - 3*bi; combined with the identity action on others).

    Actually more precisely: from the Descartes relation, the two solutions
    b4, b4' satisfy b4 + b4' = 2*(b1 + b2 + b3). So the reflection that swaps
    b4 ↔ b4' is:
        (b1, b2, b3, b4) ↦ (b1, b2, b3, 2*(b1+b2+b3) - b4)
    which is the i=4 case. General i:
        (b1, b2, b3, b4) ↦ replace bi with 2*(Σ_j≠i bj) - bi
    """
    if i < 1 or i > 4:
        raise ValueError(f"i must be in 1..4, got {i}")
    M = list(identity(4))
    row = i - 1
    # Zero out the i-th row of the identity we started with
    for c in range(4):
        M[row * 4 + c] = 0
    # Fill in: 2 in every column except i, -1 in column i
    for c in range(4):
        if c == row:
            M[row * 4 + c] = -1
        else:
            M[row * 4 + c] = 2
    return tuple(M)


R1: Matrix = _apollonian_reflection(1)
R2: Matrix = _apollonian_reflection(2)
R3: Matrix = _apollonian_reflection(3)
R4: Matrix = _apollonian_reflection(4)


def apollonian_reflections() -> Tuple[Matrix, Matrix, Matrix, Matrix]:
    """Return (R1, R2, R3, R4) — the four Apollonian reflection generators."""
    return (R1, R2, R3, R4)


# Sanity: each Ri squared should be identity (reflections are involutions).
def _verify():
    from .core import matmul
    for Ri in (R1, R2, R3, R4):
        assert matmul(Ri, Ri) == identity(4), "Apollonian reflection not involutive"
    # SL(2, Z): S^4 = I, (S*T)^3 = -I (so (ST)^6 = I), T^n ≠ I for any n≥1
    assert matmul(matmul(S, S), matmul(S, S)) == I, "S^4 != I"
    ST = matmul(S, T)
    ST3 = matmul(matmul(ST, ST), ST)
    assert ST3 == (-1, 0, 0, -1), f"(ST)^3 should be -I, got {ST3}"


_verify()  # fail-fast if generators are wrong
